# Make Ctrl+b - r reload .tmux.conf
unbind r
bind r source-file ~/.tmux.conf

# Set the termiinal
set -g default-terminal "tmux-256color"

# Set the zsh as default shell
set -g default-shell /bin/zsh

## List of plugins
# Cattpuccin
set -g @plugin 'catppuccin/tmux#v2.1.0' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g status-right ""
set -g status-left ""
run '~/.tmux/plugins/tmux/catppuccin.tmux'

# TPM
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
