# -======================================== -
#                 Options
# -======================================== -
# Make Ctrl+b - r reload .tmux.conf
unbind r
bind r source-file ~/.tmux.conf

# Fix colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Set the zsh as default shell
set -g default-shell /bin/zsh

# Keep the windows name fixed in Tmux
set-option -g allow-rename off

# -======================================== -
#                 Plugins
# -======================================== -

### Cattpuccin
set -g @plugin 'catppuccin/tmux' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
set -g status-right ""
set -g status-left ""

# Catpuccin breaks window rename - to fix it we need the following two lines
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# Run Catppuccin
run '~/.tmux/plugins/tmux/catppuccin.tmux'

### TPM
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
